import sqlite3
from pathlib import Path

DB_PATH = Path(__file__).parent / "docentes.db"

# NOTA IMPORTANTE:
# Aquí solo coloco la data en crudo, organizada por columnas.
# Tu lógica de:
#  - dividir grados profesionales / maestrías / doctorados
#  - normalizar fechas
#  - poblar docente_grado_academico
# puede ser exactamente la misma que ya usaste para el lote 2.

DOCENTES_LOTE_3 = [
    {
        "nombre_completo": "DRA. SHIRLEY EMPERATRIZ CHILET CAMA",
        "especialidad": "ARQUITECTO",
        "dni": "15347646",
        "direccion": "JR. HUAMACHUCO N° 1558-DPTO 204 JESUS MARIA LIMA",
        "correo": "shchiletc@yahoo.com",
        "telefono": "957591430 - 982567687",
        "titulos_raw": "ARQUITECTO 13-05-1991 - ABOGADA 30-03-15",
        "titulos_universidades_raw": "UNIVERSIDAD NACIONAL DE INGENIERÍA - UNIVERSIDAD ALAS PERUANAS",
        "magister_raw": "MAESTRÍA EN CIENCIAS EN PLANIFICACIÓN DEL DESARROLLO URBANO Y REGIONAL 09-05-2011",
        "magister_universidad_raw": "UNIVERSIDAD NACIONAL DE INGENIERIA",
        "doctor_raw": "DOCTORA EN MEDIO AMBIENTE Y DESARROLLO SOSTENIBLE 09-01-2013",
        "doctor_universidad_raw": "UNIVERSIDAD NACIONAL FEDERICO VILLAREAL",
    },
    {
        "nombre_completo": "DRA. SILVIA ELENA AGUIRRE ABARCA",
        "especialidad": "ABOGADO",
        "dni": "23837351",
        "direccion": "URB. MAGISTERIAL FRANCISCO SIVIRICHI N° 213",
        "correo": "silviaelenaaguirrea@hotmail.com",
        "telefono": "984307700",
        "titulos_raw": "ABOGADA 16-10-1984",
        "titulos_universidades_raw": "UNIVERSIDAD NACIONAL DE SAN ANTONIO ABAD DEL CUSCO",
        "magister_raw": "MAESTRIA EN DERECHO CON MENCION EN CIENCIAS PENALES 06-10-2011",
        "magister_universidad_raw": "UNIVERSIDAD NACIONAL MAYOR DE SAN MARCOS",
        "doctor_raw": "DOCTORA EN DERECHO Y CIENCIA POLITICA 20-03-2014",
        "doctor_universidad_raw": "UNIVERSIDAD NACIONAL MAYOR DE SAN MARCOS",
    },
    {
        "nombre_completo": "DRA. SIVELY LUZ MERCADO MAMANI",
        "especialidad": "CIRUJANO DENTISTA",
        "dni": "43700814",
        "direccion": "PSJE. JUAN JOSE CALLE 161 LIMA",
        "correo": "goty20@hotmail.com",
        "telefono": "989071293",
        "titulos_raw": "CIRUJANO DENTISTA 23-11-2006",
        "titulos_universidades_raw": "UNIVERSIDAD CATÓLICA DE SANTA MARÍA",
        "magister_raw": "MAESTRÍA EN CIENCIAS SALUD PÚBLICA CON MENCIÓN EN GERENCIA DE SERVICIOS DE SALUD 30-04-2010 - MAESTRÍA EN SALUD ESTOMATOLOGÍA 11-11-2016",
        "magister_universidad_raw": "UNIVERSIDAD NACIONAL DE SAN AGUSTIN DE AREQUIPA - UNIVERSIDAD ANDINA NESTOR CACERES VELASQUEZ",
        "doctor_raw": "DOCTOR EN CIENCIAS SALUD PÚBLICA 17-10-2014",
        "doctor_universidad_raw": "UNIVERSIDAD NACIONAL DE SAN AGUSTIN DE AREQUIPA",
    },
    {
        "nombre_completo": "DRA. SOFIA VISA QUISPE",
        "especialidad": "LICENCIADO EN EDUCACIÓN",
        "dni": "23909488",
        "direccion": "CALLE TRES MARIAS B-6 SANTIAGO",
        "correo": "sofia6583@hotmail.com",
        "telefono": "992211046",
        "titulos_raw": "LICENCIADO EN EDUCACIÓN 20-05-1991",
        "titulos_universidades_raw": "UNIVERSIDAD NACIONAL DE SAN ANTONIO ABAD DEL CUSCO",
        "magister_raw": "MAESTRÍA EN DOCENCIA UNIVERSITARIA 04-08-2009",
        "magister_universidad_raw": "UNIVERSIDAD NACIONAL DE SAN ANTONIO ABAD DEL CUSCO",
        "doctor_raw": "DOCTORA EN EDUCACION 17-08-2012",
        "doctor_universidad_raw": "UNIVERSIDAD ANDINA NESTOR CACERES VELASQUEZ DE JULIACA",
    },
    {
        "nombre_completo": "DRA. URSULA ISABEL ROMANI MIRANDA",
        "especialidad": "LICENCIADO EN EDUCACIÓN",
        "dni": "40873367",
        "direccion": "CALLE PARIS 141 URB. LOS PORTALES DE JAVIER PRADO ATE",
        "correo": "ursula.romani.epel@gmail.com",
        "telefono": "924511825",
        "titulos_raw": "LICENCIADA EN EDUCACIÓN LENGUA Y LITERATURA 22-07-2007",
        "titulos_universidades_raw": "UNIVERSIDAD NACIONAL MAYOR DE SAN MARCOS",
        "magister_raw": "MAESTRÍA EN GESTIÓN Y ADMINISTRACIÓN DE LA EDUCACIÓN 24-04-2012",
        "magister_universidad_raw": "UNIVERSIDAD NACIONAL FEDERICO VILLAREAL",
        "doctor_raw": "DOCTORA EN EDUCACIÓN 12-10-2015",
        "doctor_universidad_raw": "UNIVERSIDAD NACIONAL FEDERICO VILLAREAL",
    },
    {
        "nombre_completo": "DRA. VHANYA OLENKA MALPICA RISCO",
        "especialidad": "PSICÓLOGO",
        "dni": "18140940",
        "direccion": "CALLE LAS MALVAS N° 244 DPTO 901 URB. SANTA EDELMIRA",
        "correo": "riscovhanya@gmail.com",
        "telefono": "935686619",
        "titulos_raw": "LICENCIADA EN PSICOLOGÍA 11-11-2000",
        "titulos_universidades_raw": "UNIVERSIDAD PRIVADA CESAR VALLEJO",
        "magister_raw": "MAESTRÍA EN DOCENCIA UNIVERSITARIA E INVESTIGACIÓN PEDAGÓGICA 09-03-2017",
        "magister_universidad_raw": "UNIVERSIDAD SAN PEDRO",
        "doctor_raw": "DOCTORA EN PSICOLOGIA 12-08-2024",
        "doctor_universidad_raw": "UNIVERSIDAD PRIVADA CESAR VALLEJO",
    },
    {
        "nombre_completo": "DRA. WILMA YECELA LIVIA ROBALINO",
        "especialidad": "ABOGADO",
        "dni": "00008910",
        "direccion": "AV. JOSE LEAL N°673 DISTRITO DE LINCE LIMA",
        "correo": "rosablanca_8@hotmail.com",
        "telefono": "999544405",
        "titulos_raw": "ABOGADO 28-12-2005",
        "titulos_universidades_raw": "UNIVERSIDAD INCA GARCILAZO DE LA VEGA",
        "magister_raw": "MAESTRÍA EN DERECHO REGISTRAL Y NOTARIAL 01-03-2013",
        "magister_universidad_raw": "UNIVERSIDAD INCA GARCILAZO DE LA VEGA",
        "doctor_raw": "DOCTORA EN DERECHO 08-08-2013",
        "doctor_universidad_raw": "UNIVERSIDAD INCA GARCILAZO DE LA VEGA",
    },
    {
        "nombre_completo": "DRA. YRMA POZO REYES",
        "especialidad": "LICENCIADO EN EDUCACIÓN",
        "dni": "07049263",
        "direccion": "AV. GRAL. MANUEL VIVANCO N° 958 DPTO B-202",
        "correo": "yrmapozoreyes@gmail.com",
        "telefono": "998600530",
        "titulos_raw": "LICENCIADA EN EDUCACIÓN ESPECIALIDAD FÍSICA Y MATEMÁTICA 29-09-1987",
        "titulos_universidades_raw": "UNIVERSIDAD NACIONAL MAYOR DE SAN MARCOS",
        "magister_raw": "MAESTRÍA EN EDUCACIÓN MENCIÓN EN DOCENCIA EN EL NIVEL SUPERIOR 04-12-2008",
        "magister_universidad_raw": "UNIVERSIDAD NACIONAL MAYOR DE SAN MARCOS",
        "doctor_raw": "DOCTOR EN EDUCACIÓN 22-03-2024",
        "doctor_universidad_raw": "UNIVERSIDAD NACIONAL FEDERICO VILLAREAL",
    },
    {
        "nombre_completo": "DRA. YSABEL MASIAS YNOCENCIO",
        "especialidad": "PSICÓLOGO",
        "dni": "23984083",
        "direccion": "LOS SAUCES G-5",
        "correo": "ymasias@uandina.edu.pe",
        "telefono": "984284490",
        "titulos_raw": "LICENCIADA EN PSICOLOGIA 16-12-1988",
        "titulos_universidades_raw": "UNIVERSIDAD RICARDO PALMA",
        "magister_raw": "MAESTRÍA EN PSICOLOGÍA EDUCACIONAL 28-02-2007",
        "magister_universidad_raw": "UNIVERSIDAD PERUANA CAYETANO HEREDIA",
        "doctor_raw": "DOCTORA EN PSICOLOGÍA 12-11-2007",
        "doctor_universidad_raw": "UNIVERSIDAD NACIONAL MAYOR DE SAN MARCOS",
    },
    {
        "nombre_completo": "MG RENZO GUILLERMO ORTIZ DIAZ",
        "especialidad": "ABOGADO",
        "dni": "07267102",
        "direccion": "JR. LIBERTAD H-1 DPTO 301 URB MATEO PUMACAHUA WANCHAQ",
        "correo": "renzortiz@gmail.com",
        "telefono": "980715267",
        "titulos_raw": "ABOGADO 26-05-199",
        "titulos_universidades_raw": "UNIVERSIDAD DE SAN MARTIN DE PORRES",
        "magister_raw": "MAESTRÍA EN DERECHO REGISTRAL Y NOTARIAL 11-06-2019",
        "magister_universidad_raw": "UNIVERSIDAD ANDINA DEL CUSCO",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. ADOLFO CALLO CHOQUEVILCA",
        "especialidad": "ECONOMISTA",
        "dni": "23844092",
        "direccion": "PROLONGACIÓN LIMA 614 LIMA SANTIAGO DE SURCO",
        "correo": "adolfocallo@gmail.com",
        "telefono": "966488600",
        "titulos_raw": "ECONOMISTA 30-12-1993",
        "titulos_universidades_raw": "UNIVERSIDAD NACIONAL DE SAN ANTONIO ABAD DEL CUSCO",
        "magister_raw": "MAESTRÍA EN DIRECCIÓN DE EMPRESAS 21-07-2009",
        "magister_universidad_raw": "UNIVERSIDAD ESAN",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. ALEJANDRO BORDA IZQUIERDO",
        "especialidad": "LICENCIADO EN ENFERMERÍA",
        "dni": "08300283",
        "direccion": "RIO MAJES S/N CDRA 37 AV. PROCERES DE LA INDEPENDENCIA",
        "correo": "abordai@yahoo.com",
        "telefono": "996612444",
        "titulos_raw": "LICENCIADO EN ENFERMERÍA 28-08-1987",
        "titulos_universidades_raw": "UNIVERSIDAD NACIONAL DE SAN CRISTOBAL DE HUAMANGA",
        "magister_raw": "MAESTRÍA EN SALUD PÚBLICA 16-08-2012",
        "magister_universidad_raw": "UNIVERSIDAD PRIVADA NORBERT WIENER",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. ALEJANDRO VLADIMIR DELGADO CAMACHO",
        "especialidad": "LICENCIADO EN ADMINISTRACIÓN",
        "dni": "40350425",
        "direccion": "URB. LA FLORIDA PSJE LOS LIRIOS L-15 WANCHAQ CUSCO",
        "correo": "alejanndrovdelgado@gmail.com",
        "telefono": "974782267",
        "titulos_raw": "LICENCIADO EN ADMINISTRACIÓN 21-02-2007",
        "titulos_universidades_raw": "UNIVERSIDAD NACIONAL DE SAN ANTONIO ABAD DEL CUSCO",
        "magister_raw": "MAESTRÍA EN ADMINISTRACIÓN DE EMPRESAS 13-12-2007",
        "magister_universidad_raw": "UNIVERSIDAD PERUANA DE CIENCIAS APLICADAS",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. ALVARO HORACIO FLORES BOZA",
        "especialidad": "INGENIERO CIVIL",
        "dni": "23858562",
        "direccion": "URB. MARISCAL GAMARRA EDIF. A-13 DPTO. 415",
        "correo": "alvarohoracio25@hotmail.com",
        "telefono": "947526765",
        "titulos_raw": "INGENIERO CIVIL 17-12-1990",
        "titulos_universidades_raw": "UNIVERSIDAD NACIONAL DE SAN ANTONIO ABAD DEL CUSCO",
        "magister_raw": "MAESTRIA EN RECURSOS HIDRICOS Y MEDIO AMBIENTE 05-01-2015",
        "magister_universidad_raw": "UNIVERSIDAD NACIONAL DE SAN ANTONIO ABAD DEL CUSCO",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. ANA ELIZABETH AGUIRRE ABARCA",
        "especialidad": "INGENIERO QUÍMICO",
        "dni": "23825349",
        "direccion": "",
        "correo": "aaguirre@uandina.edu.pe",
        "telefono": "984038897",
        "titulos_raw": "INGENIERO QUIMICO 23-10-1984",
        "titulos_universidades_raw": "UNIVERSIDAD NACIONAL DE SAN ANTONIO ABAD DEL CUSCO",
        "magister_raw": "MAESTRÍA EN EDUCACIÓN MENCIÓN EN DOCENCIA E INVESTIGACIÓN EN EDUCACIÓN SUPERIOR 24-11-2004",
        "magister_universidad_raw": "UNIVERSIDAD PERUANA CAYETANO HEREDIA",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. ANGELA MERCEDES AURORA ITURRIA HERMOZA",
        "especialidad": "LICENCIADO EN EDUCACIÓN",
        "dni": "08741759",
        "direccion": "JR. BOLOGNESI 785 DPTO C-102",
        "correo": "aiturria@pucp.pe",
        "telefono": "997707161",
        "titulos_raw": "LICENCIADA EN EDUCACIÓN ESPECIALIDAD EN EDUCACIÓN PRIMARIA 02-11-1988",
        "titulos_universidades_raw": "PONTIFICIA UNIVERSIDAD CATOLICA DEL PERU",
        "magister_raw": "MAESTRÍA EN EDUCACIÓN MENCIÓN EN GESTIÓN DE LA EDUCACIÓN",
        "magister_universidad_raw": "PONTIFICIA UNIVERSIDAD CATOLICA DEL PERU",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. ANIBAL TORRES CASTILLO",
        "especialidad": "LICENCIADO EN ADMINISTRACIÓN",
        "dni": "08677294",
        "direccion": "JR. JUNIN 881 TORRE \"B\" DPTO 1202 MAGDALENA",
        "correo": "anibaltorres63@hotmail.com",
        "telefono": "941809999",
        "titulos_raw": "LICENCIADO EN ADMINISTRACIÓN 05-06-2000",
        "titulos_universidades_raw": "UNIVERSIDAD NACIONAL MAYOR DE SAN MARCOS",
        "magister_raw": "MAESTRÍA EN ADMINISTRACIÓN DE NEGOCIOS 28-09-2011",
        "magister_universidad_raw": "PONTIFICIA UNIVERSIDAD CATÓLICA DEL PERÚ",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. ARMANDO MARTINEZ BACA",
        "especialidad": "ECONOMISTA",
        "dni": "23810015",
        "direccion": "MARISCAL GAMARRA II ETAPA ZONA 1-B-3",
        "correo": "armanmb@hotmail.com",
        "telefono": "981686389",
        "titulos_raw": "ECONOMISTA 05-08-1986",
        "titulos_universidades_raw": "UNIVERSIDAD NACIONAL DE SAN ANTONIO ABAD DEL CUSCO",
        "magister_raw": "MAESTRÍA EN ECONOMÍA MENCIÓN EN ECONOMÍA Y FINANZAS DE LA EMPRESA 24-11-2016",
        "magister_universidad_raw": "UNIVERSIDAD NACIONAL DE SAN ANTONIO ABAD DEL CUSCO",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. ARTURO ZUÑIGA BLANCO",
        "especialidad": "LICENCIADO EN MATEMÁTICAS",
        "dni": "46452024",
        "direccion": "CALLE HOSPITAL 464 I-22, SAN JERÓNIMO CUSCO",
        "correo": "arturo.z172014@gmail.com",
        "telefono": "984154358",
        "titulos_raw": "LICENCIADO EN MATEMÁTICA MENCIÓN ESTADÍSTICA 04-03-2014",
        "titulos_universidades_raw": "UNIVERSIDAD NACIONAL DE SAN ANTONIO ABAD DEL CUSCO",
        "magister_raw": "MAESTRÍA EN ESTADÍSTICA E INVESTIGACIÓN CIENTÍFICA 28-08-2018",
        "magister_universidad_raw": "UNIVERSIDAD ANDINA DEL CUSCO",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. CARLOS PEREZ PEREZ",
        "especialidad": "LICENCIADO EN ENFERMERÍA",
        "dni": "27437465",
        "direccion": "CALLE 6 DE AGOSTO 467 DPTO 203 JESUS MARÍA",
        "correo": "carlosperez100@gmail.com",
        "telefono": "994984228",
        "titulos_raw": "LICENCIADO EN ENFERMERÍA 18-01-2002 - LICENCIADO EN ADMINISTRACIÓN 09-04-2018",
        "titulos_universidades_raw": "UNIVERSIDAD NACIONAL DE CAJAMARCA - UNIVERSIDAD PRIVADA CÉSAR VALLEJO",
        "magister_raw": "MAESTRÍA EN GERENCIA DE PROYECTOS Y PROGRAMAS SOCIALES 11-11-2015",
        "magister_universidad_raw": "UNIVERSIDAD PERUANA CAYETANO HEREDIA",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. CESAR ALAN JUSTO GOMEZ",
        "especialidad": "CONTADOR PÚBLICO",
        "dni": "45517999",
        "direccion": "CALLE SAN JOSE G-4 SAN SEBASTIAN CUSCO",
        "correo": "cjustogomez@gmail.com",
        "telefono": "980297360-993559165",
        "titulos_raw": "CONTADOR PÚBLICO 23-07-2012",
        "titulos_universidades_raw": "UNIVERSIDAD NACIONAL JORGE BASADRE GROHMANN",
        "magister_raw": "MAESTRÍA EN CONTRATACIÓN PÚBLICA (Reconocimiento)",
        "magister_universidad_raw": "UNIVERSIDAD DE CASTILLA - LA MANCHA",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. CESAR AUGUSTO DELGADO PIZARRO",
        "especialidad": "INGENIERO INDUSTRIAL",
        "dni": "07535016",
        "direccion": "CALLE JOSE SABOGAL N°577 - 503 URB. LA AURORA",
        "correo": "cesar.delgado4@gmail.com",
        "telefono": "995725485 - 995951133",
        "titulos_raw": "INGENIERO INDUSTRIAL 19-05-1995",
        "titulos_universidades_raw": "UNIVERSIDAD NACIONAL MAYOR DE SAN MARCOS",
        "magister_raw": "MAESTRÍA UNIVERSITARIA EN INVESTIGACIÓN PARTICIPATIVA PARA EL DESARROLLO LOCAL 26-07-2017",
        "magister_universidad_raw": "UNIVERSIDAD COMPLUTENSE DE MADRID",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. CESAR PANIAGUA CHACON",
        "especialidad": "CONTADOR PÚBLICO",
        "dni": "25000163",
        "direccion": "URB. LA FLORIDA CALLE LOS JAZMINES K-11 CUSCO",
        "correo": "cesarpaniagua2000@yahoo.es",
        "telefono": "987792520",
        "titulos_raw": "CONTADOR PÚBLICO 26-06-2002 - INGENIERO CIVIL 16-11-2005",
        "titulos_universidades_raw": "UNIVERSIDAD ANDINA DEL CUSCO - UNIVERSIDAD NACIONAL DE SAN ANTONIO ABAD DEL CUSCO",
        "magister_raw": "MAESTRÍA EN DOCENCIA UNIVERSITARIA 12-03-15",
        "magister_universidad_raw": "UNIVERSIDAD ANDINA DEL CUSCO",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. CHARLES AUGUSTO HUAMANI SALDAÑA",
        "especialidad": "MÉDICO CIRUJANO",
        "dni": "42357718",
        "direccion": "URB. DANIEL ALCIDES CARRION B-14 SAN SEBASTIAN",
        "correo": "huamani.ca@gmail.com",
        "telefono": "992814710",
        "titulos_raw": "MEDICO CIRUJANO 11-03-2010",
        "titulos_universidades_raw": "UNIVERSIDAD NACIONAL MAYOR DE SAN MARCOS",
        "magister_raw": "MAESTRÍA EN CIENCIAS EN INVESTIGACIÓN EPIDEMIOLÓGICA 26-11-2014",
        "magister_universidad_raw": "UNIVERSIDAD PERUANA CAYETANO HEREDIA",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. CLEVER ABELARDO MONTALVO LOAIZA",
        "especialidad": "CONTADOR PÚBLICO",
        "dni": "23849535",
        "direccion": "DPTO. 102 URB. JOSE CARLOS MARIATEGUI MZ. D LT. 26",
        "correo": "clevermontalvo@yahoo.es",
        "telefono": "963411254",
        "titulos_raw": "CONTADOR PÚBLICO 02-10-1995",
        "titulos_universidades_raw": "UNIVERSIDAD NACIONAL DE SAN ANTONIO ABAD DEL CUSCO",
        "magister_raw": "MAESTRÍA EN CONTABILIDAD MENCIÓN EN AUDITORIA 16-07-2014",
        "magister_universidad_raw": "UNIVERSIDAD NACIONAL DE SAN ANTONIO ABAD DEL CUSCO",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. DANTE HORACIO OLIVERA MAYO",
        "especialidad": "MÉDICO CIRUJANO",
        "dni": "23825212",
        "direccion": "KANTUS 16-F 1RA ETAPA MARISCAL GAMARRA CUSCO",
        "correo": "danteoliveramayo@hotmail.com",
        "telefono": "974404272",
        "titulos_raw": "MEDICO CIRUJANO 12-10-1989",
        "titulos_universidades_raw": "UNIVERSIDAD NACIONAL DE SAN ANTONIO ABAD DEL CUSCO",
        "magister_raw": "MAESTRÍA EN DOCENCIA UNIVERSITARIA 09-07-1998 - MAESTRÍA EN CONTABILIDAD MENCIÓN EN AUDITORÍA 25-07-2012 - MAESTRÍA EN ADMINISTRACIÓN MENCIÓN EN GESTIÓN PUBLICA Y DESARROLLO EMPRESARIAL 03-07-2012",
        "magister_universidad_raw": "UNIVERSIDAD NACIONAL DE SAN ANTONIO ABAD DEL CUSCO - UNIVERSIDAD NACIONAL DE SAN ANTONIO ABAD DEL CUSCO - UNIVERSIDAD NACIONAL DE SAN ANTONIO ABAD DEL CUSCO",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. DIANA MERCERDES REVILLA FIGUEROA",
        "especialidad": "LICENCIADO EN EDUCACIÓN",
        "dni": "07655540",
        "direccion": "JIRON ECHENIQUE 960 B MAGDALENA DEL MAR LIMA",
        "correo": "dmrevilla@pucp.pe",
        "telefono": "999851147",
        "titulos_raw": "LICENCIADO EN EDUCACIÓN 23-03-1988",
        "titulos_universidades_raw": "PONTIFICIA UNIVERSIDAD CATOLICA DEL PERU",
        "magister_raw": "MAESTRÍA EN EDUCACIÓN CON MENCIÓN EN PLANIFICACIÓN DE LA EDUCACIÓN 12-05-2004",
        "magister_universidad_raw": "PONTIFICIA UNIVERSIDAD CATÓLICA DEL PERÚ",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. DINA LIZBETH APARICIO JURADO",
        "especialidad": "PSICÓLOGO",
        "dni": "42482929",
        "direccion": "RESIDENCIAL HUANCARO AVENIDA ASOCIACIÓN I-22-B DPTO 102 SANTIAGO CUSCO",
        "correo": "daparicio@uandina.edu.pe",
        "telefono": "984327462",
        "titulos_raw": "PSICOLOGA 28-05-2008",
        "titulos_universidades_raw": "UNIVERSIDAD ANDINA DEL CUSCO",
        "magister_raw": "MAESTRÍA EN PSICOLOGÍA CLÍNICA 23-10-2019",
        "magister_universidad_raw": "UNIVERSIDAD PERUANA CAYETANO HEREDIA",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. DONNY ALEJANDRO HOLGUIN HERRERA",
        "especialidad": "INGENIERO INDUSTRIAL",
        "dni": "45619477",
        "direccion": "URB. LOS NOGALES S-11",
        "correo": "donny.holguin.herrera@gmail.com",
        "telefono": "930129117",
        "titulos_raw": "INGENIERO INDUSTRIAL 05-11-2014",
        "titulos_universidades_raw": "UNIVERSIDAD ANDINA DEL CUSCO",
        "magister_raw": "MAESTRÍA EN ADMINISTRACIÓN ESTRATÉGICA DE EMPRESAS 15-05-2019",
        "magister_universidad_raw": "PONTIFICIA UNIVERSIDAD CATÓLICA DEL PERÚ",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. EDDA MARIBEL OBREGON CARRERA",
        "especialidad": "ABOGADO",
        "dni": "08664362",
        "direccion": "JR. RÍO UCAYALI N° 5365 URB. VILLA DEL NORTE LOS OLIVOS",
        "correo": "e_obregon@hotmail.com",
        "telefono": "993548143",
        "titulos_raw": "ABOGADO 22-04-1998",
        "titulos_universidades_raw": "UNIVERSIDAD NACIONAL FEDERICO VILLAREAL",
        "magister_raw": "MAESTRÍA EN DERECHO CON MENCIÓN EN CIVIL Y COMERCIAL 26-10-2017",
        "magister_universidad_raw": "UNIVERSIDAD NACIONAL HERMILIO VALDIZAN DE HUÁNUCO",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. EDISON ALAN ALVES CHOQUE",
        "especialidad": "LICENCIADO EN ADMINISTRACIÓN",
        "dni": "40551283",
        "direccion": "AV. DE LA CULTURA 2130 WANCHAQ CUSCO",
        "correo": "ealvescusco@hotmail.com",
        "telefono": "984115155",
        "titulos_raw": "LICENCIADO EN ADMINISTRACIÓN 16-02-2011",
        "titulos_universidades_raw": "UNIVERSIDAD NACIONAL DE SAN ANTONIO ABAD DEL CUSCO",
        "magister_raw": "MAESTRÍA EN CIENCIAS EMPRESARIALES MENCIÓN EN GESTIÓN DE PROYECTOS 09-02-2017",
        "magister_universidad_raw": "UNIVERSIDAD SAN IGNACIO DE LOYOLO S.A",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. EDITH GUDIELA PINTO PAGAZA",
        "especialidad": "LICENCIADO EN ENFERMERÍA",
        "dni": "23985215",
        "direccion": "URB. MARISCAL GAMARRA A-1-1-205- CUSCO",
        "correo": "epintopagaza@gmail.com",
        "telefono": "984622733",
        "titulos_raw": "LICENCIADO EN ENFERMERÍA 08-04-1987 - ABOGADA 11-08-2000",
        "titulos_universidades_raw": "UNIVERSIDAD NACIONAL DE SAN ANTONIO ABAD DEL CUSCO - UNIVERSIDAD ANDINA DEL CUSCO",
        "magister_raw": "MAESTRÍA EN DOCENCIA UNIVERSITARIA GESTIÓN EDUCATIVA 13-12-2010",
        "magister_universidad_raw": "UNIVERSIDAD ALAS PERUANAS",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. EDWARD ANIBAL MORANTE RIOS",
        "especialidad": "LICENCIADO EN ADMINISTRACIÓN",
        "dni": "23930443",
        "direccion": "URB. SAN FRANCISCO K-5",
        "correo": "edward_mr55@hotmail.com",
        "telefono": "984728208",
        "titulos_raw": "LICENCIADO EN ADMINISTRACIÓN 14-12-2007",
        "titulos_universidades_raw": "UNIVERSIDAD ANDINA DEL CUSCO",
        "magister_raw": "MAESTRÍA EN GESTIÓN DE LA EDUCACIÓN 07-08-2019",
        "magister_universidad_raw": "UNIVERSIDAD CATÓLICA DE SANTA MARÍA",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. EDWIN GERMAN GRANDEZ SOLIS",
        "especialidad": "LICENCIADO EN ADMINISTRACIÓN",
        "dni": "42143537",
        "direccion": "JR. JACARANDA 262 CALCA",
        "correo": "edwingrandez@gmail.com",
        "telefono": "920578018",
        "titulos_raw": "LICENCIADO EN ADMINISTRACIÓN DE NEGOCIOS INTERNACIONALES 09-07-2010",
        "titulos_universidades_raw": "UNIVERSIDAD DE SAN MARTIN DE PORRES",
        "magister_raw": "MAESTRÍA EN MARKETING Y NEGOCIOS INTERNACIONALES 05-12-2016",
        "magister_universidad_raw": "UNIVERSIDAD NACIONAL FEDERICO VILLAREAL",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. EIGNER ROMAN VILLEGAS",
        "especialidad": "INGENIERO CIVIL",
        "dni": "23928061",
        "direccion": "URB. KENNEDY \"A\" B-36",
        "correo": "nayacusco@hotmail.com",
        "telefono": "957349247",
        "titulos_raw": "INGENIERO CIVIL 05-01-2001",
        "titulos_universidades_raw": "UNIVERSIDAD NACIONAL DE SAN ANTONIO ABAD DEL CUSCO",
        "magister_raw": "MAESTRÍA EN INGENIERÍA CIVIL MENCIÓN EN GEOTÉCNIA Y VÍAS TERRESTRES 22-10-2014",
        "magister_universidad_raw": "UNIVERSIDAD ALAS PERUANAS",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. ELADIO VLADIMIRO LEON PINO MENA",
        "especialidad": "ABOGADO",
        "dni": "23856121",
        "direccion": "AV. GASTON ZAPATA N°421 WANCHAQ",
        "correo": "evlpm1264@gmail.com",
        "telefono": "974787212",
        "titulos_raw": "ABOGADO 21-09-2001",
        "titulos_universidades_raw": "UNIVERSIDAD TECNOLÓGICA DE LOS ANDES",
        "magister_raw": "MAESTRÍA EN GESTIÓN PÚBLICA 27-04-2016",
        "magister_universidad_raw": "UNIVERSIDAD PRIVADA CESAR VALLEJO",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. ELIAS SEGOVIA PUMA",
        "especialidad": "PSICÓLOGO",
        "dni": "24383900",
        "direccion": "URB. SAN JUDAS GRANDE CALLE \"Q\" A - 6",
        "correo": "elias_segovia@hotmail.com",
        "telefono": "984768230",
        "titulos_raw": "LICENCIADO EN PSICOLOGÍA HUMANA 21-04-2016 - LICENCIADO ENFERMERÍA 17-09-1995",
        "titulos_universidades_raw": "UNIVERSIDAD ALAS PERUANAS - UNIVERSIDAD NACIONAL DE SAN ANTONIO ABAD DEL CUSCO",
        "magister_raw": "MAESTRÍA EN SALUD PÚBLICA MENCIÓN EN SALUD OCUPACIONAL 09-12-2016",
        "magister_universidad_raw": "UNIVERSIDAD NACIONAL DE SAN ANTONIO ABAD DEL CUSCO",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. ELVIR FRANS ARELLANO GAMARRA",
        "especialidad": "BIÓLOGO",
        "dni": "41777894",
        "direccion": "URB. TTIO O-2-10 WANCHAQ",
        "correo": "elvirfransarellano@gmail.com",
        "telefono": "987360593",
        "titulos_raw": "LICENCIADO EN BIOLOGÍA 10-12-2008",
        "titulos_universidades_raw": "UNIVERSIDAD NACIONAL PEDRO RUIZ GALLO",
        "magister_raw": "MAESTRÍA EN MEDIO AMBIENTE Y SISTEMAS INTEGRADOS DE GESTIÓN 21-05-2021",
        "magister_universidad_raw": "UNIVERSIDAD NACIONAL DE SAN AGUSTIN AREQUIPA",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. EMILIO PALOMINO OLIVERA",
        "especialidad": "INGENIERO DE SISTEMAS",
        "dni": "23860669",
        "direccion": "CONJ. HAB. COVIPOL MZ. C LT. 7",
        "correo": "epalominoo@uandina.edu.pe",
        "telefono": "984624442",
        "titulos_raw": "INGENIERO DE SISTEMAS (Reconocimiento)",
        "titulos_universidades_raw": "UNIVERSIDAD ESTATAL TECNICA DE TASHKENT BERUNI",
        "magister_raw": "MAESTRÍA EN INGENIERÍA (Reconocimiento)",
        "magister_universidad_raw": "UNIVERSIDAD ESTATAL TECNICA DE TASHKENT BERUNI",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. ERICK ALCCA ZELA",
        "especialidad": "INGENIERO DE SISTEMAS",
        "dni": "42955593",
        "direccion": "URB. RAMIRO PRIALE A-4",
        "correo": "ealcca@uandina.edu.pe",
        "telefono": "984360092",
        "titulos_raw": "INGERNIERO DE SISTEMAS 15-04-2008",
        "titulos_universidades_raw": "UNIVERSIDAD ANDINA DEL CUSCO",
        "magister_raw": "MAESTRÍA EN ADMINISTRACIÓN DE NEGOCIOS 27-06-2018",
        "magister_universidad_raw": "UNIVERSIDAD ANDINA DEL CUSCO",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. ERICK JOEL ZUNIGA VIZCARRA",
        "especialidad": "ECONOMISTA",
        "dni": "45150991",
        "direccion": "URB. VELASCO ASTETE C-8",
        "correo": "erickzunigaconsultorjec@gmail.com",
        "telefono": "963752402",
        "titulos_raw": "ECONOMISTA 20-04-2015",
        "titulos_universidades_raw": "UNIVERSIDAD ANDINA DEL CUSCO",
        "magister_raw": "MAESTRÍA EN ADMINISTRACIÓN ESTRATÉGICA DE EMPRESAS 15-05-2019",
        "magister_universidad_raw": "PONTIFICIA UNIVERSIDAD CATÓLICA DEL PERÚ",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. ESTRELLA ROSANNA TORRES PRADA",
        "especialidad": "PSICÓLOGO",
        "dni": "08451467",
        "direccion": "REPUBLICA DOMINICANA 116-7",
        "correo": "estrellarosanna20@gmail.com",
        "telefono": "945193958",
        "titulos_raw": "LICENCIADA EN PSICOLOGIA 24-05-1993",
        "titulos_universidades_raw": "UNIVERSIDAD NACIONAL FEDERICO VILLAREAL",
        "magister_raw": "MAESTRIA EN SALUD PUBLICA 14-11-2012",
        "magister_universidad_raw": "UNIVERSIDAD NACIONAL FEDERICO VILLAREAL",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. FERNANDO FEDERICO ROMERO NEIRA",
        "especialidad": "ECONOMISTA",
        "dni": "23964430",
        "direccion": "BENAVENTE VELARDE K9 CONDOMINIO LAS ORQUIDEAS 104 MAGISTERIO CUSCO",
        "correo": "romeroneira@gmail.com",
        "telefono": "984649963",
        "titulos_raw": "LICENCIADO EN ECONOMÍA 09-12-1987",
        "titulos_universidades_raw": "PONTIFICIA UNIVERSIDAD CATOLICA DEL PERU",
        "magister_raw": "MAESTRÍA UNIVERSITARIA EN GLOBALIZACIÓN: PROCESOS SOCIALES Y POLÍTICAS ECONÓMICAS (Reconocmiento)",
        "magister_universidad_raw": "UNIVERSIDAD DEL PAÍS VASCO",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. FRANCISCO JOSE MARTINEZ SALINAS",
        "especialidad": "LICENCIADO EN EDUCACIÓN",
        "dni": "09999469",
        "direccion": "VERSALIO 344 SAN BORJA LIMA",
        "correo": "franciscoms_8m@hotmail.com",
        "telefono": "993471957",
        "titulos_raw": "LICENCIADO EN EDUCACIÓN NIVEL SECUNDARIA ESPECIALIDAD MATEMÁTICA Y FÍSICA 12-05-2006",
        "titulos_universidades_raw": "UNIVERSIDAD DE PIURA",
        "magister_raw": "MAESTRÍA EN EDUCACIÓN TEORÍAS Y PRÁCTICA EDUCATIVA 15-02-2011",
        "magister_universidad_raw": "UNIVERSIDAD ALAS PERUANAS",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. FRANKLIN GREGORIO GUTIERREZ MERINO",
        "especialidad": "ABOGADO",
        "dni": "09880997",
        "direccion": "JR. RICARDO PALMA, A-7, JR SAN MIGUEL II SAN SEBASTIAN CUSCO",
        "correo": "fg_gutierrezm@hotmail.com",
        "telefono": "998490603",
        "titulos_raw": "ABOGADO 03-10-1997",
        "titulos_universidades_raw": "UNIVERSIDAD DE SAN MARTIN DE PORRES",
        "magister_raw": "MAESTRÍA EN DERECHO CIVIL Y COMERCIAL 03-12-2019",
        "magister_universidad_raw": "UNIVERSIDAD NACIONAL MAYOR DE SAN MARCOS",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. GABRIELA OVIEDO MENA",
        "especialidad": "INGENIERO CIVIL",
        "dni": "44888919",
        "direccion": "",
        "correo": "gom.ingenieros@gmail.com",
        "telefono": "974303400",
        "titulos_raw": "INGENIERO CIVIL 06-03-2013",
        "titulos_universidades_raw": "UNIVERSIDAD NACIONAL DE SAN ANTONIO ABAD DEL CUSCO",
        "magister_raw": "MAESTRÍA EN INGENIERÍA CIVIL MENCIÓN EN HIDRÁULICA Y DE SANEAMIENTO 21-02-2022",
        "magister_universidad_raw": "UNIVERSIDAD DE SAO PAULO",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. GILBERT ALBERTO MONZON DIAZ",
        "especialidad": "LICENCIADO EN MATEMÁTICAS",
        "dni": "23974982",
        "direccion": "AVENIDA BAJA 205",
        "correo": "gmonzon@uandina.edu.pe",
        "telefono": "958069993",
        "titulos_raw": "LICENCIADO EN MATEMÁTICA 16-02-2005",
        "titulos_universidades_raw": "UNIVERSIDAD NACIONAL DE SAN ANTONIO ABAD DEL CUSCO",
        "magister_raw": "MAESTRÍA EN DOCENCIA UNIVERSITARIA E INVESTIGACIÓN PEDAGÓGICA 20-04-2017",
        "magister_universidad_raw": "UNIVERSIDAD SAN PEDRO",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. GILBERTO MENDOZA DEL MAESTRO",
        "especialidad": "ABOGADO",
        "dni": "40856192",
        "direccion": "URB. JOSE GALVEZ CALLE EL PARQUE 224 LIMA",
        "correo": "gmendoza@pucp.edu.pe",
        "telefono": "987721673",
        "titulos_raw": "ABOGADO 13-05-2009",
        "titulos_universidades_raw": "PONTIFICIA UNIVERSIDAD CATOLICA DEL PERU",
        "magister_raw": "MAESTRIA EN DERECHO CON MENCION EN DERECHO CONSTITUCIONAL Y DERECHOS HUMANOS 20-11-2012",
        "magister_universidad_raw": "UNIVERSIDAD NACIONAL MAYOR DE SAN MARCOS",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
    {
        "nombre_completo": "MG. GUILLERMO MOSQUEIRA LOVON",
        "especialidad": "ECONOMISTA",
        "dni": "23954798",
        "direccion": "CALLE PIURA 650 MIRAFLORES",
        "correo": "guillermo.mosqueira@upch.pe",
        "telefono": "998879953",
        "titulos_raw": "ECONOMISTA 14-02-1996",
        "titulos_universidades_raw": "UNIVERSIDAD NACIONAL DE SAN ANTONIO ABAD DEL CUSCO",
        "magister_raw": "MAESTRÍA EN GERENCIA DE SERVICIOS DE SALUD 13-12-2012",
        "magister_universidad_raw": "UNIVERSIDAD ESAN",
        "doctor_raw": "",
        "doctor_universidad_raw": "",
    },
]


def get_conn():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def upsert_docente_basico(conn, d):
    """
    Inserta o actualiza SOLO la parte básica en la tabla docente,
    sin tocar aún docente_grado_academico.
    """
    cur = conn.cursor()
    # Buscar por DNI
    cur.execute("SELECT id FROM docente WHERE dni = ?", (d["dni"],))
    row = cur.fetchone()

    if row:
        docente_id = row["id"]
        cur.execute(
            """
            UPDATE docente
            SET nombre_completo = ?,
                especialidad = ?,
                direccion = ?,
                correo = ?,
                telefono = ?,
                updated_at = datetime('now')
            WHERE id = ?
            """,
            (
                d["nombre_completo"],
                d["especialidad"],
                d["direccion"],
                d["correo"],
                d["telefono"],
                docente_id,
            ),
        )
    else:
        # split de nombres rápido (igual que usaste antes: últimos 2 tokens apellidos)
        nombre_sin_tratamiento = (
            d["nombre_completo"]
            .replace("DR.", "")
            .replace("DRA.", "")
            .replace("MG.", "")
            .replace("MG", "")
            .strip()
        )
        partes = nombre_sin_tratamiento.split()
        if len(partes) >= 3:
            apellido_paterno = partes[-2]
            apellido_materno = partes[-1]
            nombres = " ".join(partes[:-2])
        elif len(partes) == 2:
            apellido_paterno = partes[1]
            apellido_materno = ""
            nombres = partes[0]
        else:
            apellido_paterno = ""
            apellido_materno = ""
            nombres = nombre_sin_tratamiento

        cur.execute(
            """
            INSERT INTO docente (
                apellido_paterno, apellido_materno, nombres,
                nombre_completo, especialidad, dni,
                direccion, correo, telefono
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                apellido_paterno,
                apellido_materno,
                nombres,
                d["nombre_completo"],
                d["especialidad"],
                d["dni"],
                d["direccion"],
                d["correo"],
                d["telefono"],
            ),
        )
        docente_id = cur.lastrowid

    conn.commit()
    return docente_id


def main():
    print(f"Usando base de datos: {DB_PATH}")
    conn = get_conn()

    for d in DOCENTES_LOTE_3:
        docente_id = upsert_docente_basico(conn, d)
        print(f"✔ Docente (datos básicos) procesado: {d['nombre_completo']} (id={docente_id})")

    print(f"\n✅ Lote 3 completado. Docentes procesados: {len(DOCENTES_LOTE_3)}")


if __name__ == "__main__":
    main()
